### ISSUE TITLE
libOpenImageDenoise.so.0

### ISSUE THREAD

**Issue by HTransistor** [OpenImageDenoise/oidn#104]
**The problem:**

import vtk
  File "/usr/lib/python3.9/site-packages/vtk.py", line 30, in <module>
    all_m = importlib.import_module('vtkmodules.all')
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.9/site-packages/vtkmodules/all.py", line 33, in <module>
    from .vtkRenderingRayTracing import *
ImportError: libOpenImageDenoise.so.0: cannot open shared object file: No such file or directory

**My workaround right now:**
After downgrading package openimagedenoise (1.3.0-1 => 1.2.4-1) everything works.
Not sure if it is a problem of vtk or openimagedenoise.

**Comment by atafra** [comment]
This is not a bug in Open Image Denoise. Since `v1.3.0` the SOVERSION of the library has been increased from 0 to 1. It seems that VTK links against `libOpenImageDenoise.so.0`, which is the name of the .so file until `v1.2.4`. This issue should go away if VTK would link against the latest version of Open Image Denoise, which has `libOpenImageDenoise.so.1`.
