### ISSUE TITLE
Not too clear cleanAux parameter definition.

### ISSUE THREAD

**Issue by FrankEscobar** [OpenImageDenoise/oidn#114]
- Added the cleanAux filter parameter for further improving quality when the auxiliary feature (albedo, normal) images are noise-free.

- Added support for denoising auxiliary feature images, which can be used together with the new cleanAux parameter for improving quality when the auxiliary images are noisy (recommended for final frame denoising).

**cleanAux** should be used when "images are noise-free" or " for improving quality when the auxiliary images are noisy" ?

**Comment by atafra** [comment]
I'm not sure what's the issue. These are two completely separate features, which can be used together. As the first item says, `cleanAux` should be used when the **auxiliary** images are noise-free.

The second item mentions a completely different feature: the possibility to **denoise** auxiliary images, which of course make sense only if those are noisy. However, if you denoise the auxiliary features this way, you can now use `cleanAux` for denoising the beauty image because now the auxiliary features have become noise-free.

But the quoted ext is just from the changelog. A much more detailed description can be found in the documentation.

**Comment by FrankEscobar** [comment]
So there are these posibilities:

- Keep working as before.
- Use the new methods:
   - If you know that your buffers are clean set cleanAux to true.
   - Else you can remove the noise from the buffers (I think that this could be available on the help pdf, but I didn't read it yet).
   
Is that ok? Thank you for your time Attila!

**Comment by atafra** [comment]
Yes, these are the possibilities. It's important to set `cleanAux` to true in the third case too, to get all the quality benefits. The documentation contains more details about denoising the albedo and normal buffers.

**Comment by FrankEscobar** [comment]
Thank you I've readed the .pdf and it seems to be pretty clear but unfortunately there is no code snippet in oidnDenoise.cpp so I don't know what should we do to prefilter the auxiliar channels if needed?

I bet it shouldn't be as simple as execute the RT filter in that channels too.

Thank you in advance!

**Comment by atafra** [comment]
There is indeed no code snippet, but pre-filtering should be straightforward. You just need to do execute the `RT` filter for the albedo and normal images first, as described in the documentation:

> It is possible to denoise auxiliary images as well, in which case only the respective auxiliary image has to be specified as input, instead of the color image.

Then, you need to execute the filter for the beauty image using the denoised albedo and normal images as additional inputs, and don't forget to set `cleanAux` to true. It is recommended to create three separate RT filters to avoid expensive re-initialization if you want to denoise multiple frames this way.
