### ISSUE TITLE
CUDA/Vulkan Interop for optimally tiled images

### ISSUE THREAD

**Issue by chrisakriv-rfpro** [OpenImageDenoise/oidn#169]
Hi. It's currently possible to share the memory of Vulkan images that use linear tiling (`VK_IMAGE_TILING_LINEAR `). Do you also plan to support optimally tiled images (`VK_IMAGE_TILING_OPTIMAL`)?

**Comment by atafra** [comment]
Hi. Currently images can be shared only through buffer sharing. This way only `VK_IMAGE_TILING_LINEAR` can be supported because `VK_IMAGE_TILING_OPTIMAL` is an unknown, device-dependent layout.

So to be able to share images with `VK_IMAGE_TILING_OPTIMAL` buffer sharing cannot be used, and image/texture sharing would be necessary. This may be supported in the future there are no immediate plans for this yet.

**Comment by akrvx** [comment]
Fair enough, thanks.
