### ISSUE TITLE
Set TileAlignment and TileOverlap methods not implemented

### ISSUE THREAD

**Issue by BigFranklin1** [OpenImageDenoise/oidn#184]
The `UNetFilter::setInt` method only handles quality and maxMemoryMB. While the TileAlignment and TileOverlap are passed in, it goes to the warning that unknown filter parameter or type mismatch.

**Comment by BigFranklin1** [comment]
Hi atafra! Thank you for your quick reply! I did not notice that tileAlignment is labeled as constant in the manual. The manual says that "when manually denoising in tiles....", does it mean that I can specify these params for a better performance in any situation?

![image](https://github.com/OpenImageDenoise/oidn/assets/47847885/39c17da8-88da-4477-b723-68046f0dcf71)

**Comment by atafra** [comment]
You cannot specify these because they are specific to the denoising algorithm. This is why they are constants. But you can query these if you need to denoise a large image in tiles without relying on OIDN to do it transparently (e.g. if you want to denoise different parts of the image on different machines). You need to know these values to denoise the image correctly this way.
