### ISSUE TITLE
Different details between V0.8.1 and V1.0.0

### ISSUE THREAD

**Issue by seghier** [OpenImageDenoise/oidn#40]
Hello ; i test version 0.8.1 and the new version 1.0.0
The image output from the old version looks better in the details unlike the new version more blurry 
V 0.8.1
![0 8 1](https://user-images.githubusercontent.com/6026588/64486024-2dc63500-d228-11e9-98dd-559b0f180bb1.jpg)
V 1.0.0
![1 0 0](https://user-images.githubusercontent.com/6026588/64486025-2dc63500-d228-11e9-9d97-44eab918e477.jpg)

**Comment by atafra** [comment]
Hi! v1.0.0 significantly improves overall image quality, but in some rare cases the quality might be slightly lower. Unfortunately it's not possible to avoid quality regression in every possible case. However in this case I'm not sure that the quality is overall worse with v1.0.0. v0.8.1 is less blurry because it failed to denoise certain areas. These are not useful details but noise which the denoiser should filter out.
