### ISSUE TITLE
Request for samples

### ISSUE THREAD

**Issue by lateralpunk** [OpenImageDenoise/oidn#5]
Related question about the denoise sample. Can you provide some sample data files and documentation? I tried downloading https://openimagedenoise.github.io/images/sponza_16spp_input.jpg, using ImageMagick to convert it to PFM, but was very successful when running denoise (came back with an Error: option expected). I figure my input isn't correct.
here is a response: https://github.com/OpenImageDenoise/oidn/issues/1#issuecomment-459767919 that is helpful, but I'm actually just looking for actual data sets.

**Comment by alecksmart** [comment]
I second this. I shoot analog film and would be interested in using a command line utility.

**Comment by atafra** [comment]
Open Image Denoise does not work with photos. It's for ray tracing only (as written in the title and documentation).

**Comment by jomeng** [comment]
We have not released test datasets as of yet, but will keep your request in mind going forward. 

Converting from jpg to pfm will probably not work as expected because of the lossy compression. Open Image Denoise generally requires [32 bit float](https://openimagedenoise.github.io/documentation.html) input data, though it can be low dynamic range (values in [0, 1]) or high dynamic range (any positive value).
