### ISSUE TITLE
[OIDN]: invalid tensor format

### ISSUE THREAD

**Issue by jiapei100** [OpenImageDenoise/oidn#75]
I rebuilt everything on Ubuntu 18.04, and what is the backend Tensor **OIDN** is based upon? What's more, do you have an **TEST suite** for the effectiveness of the **built OIDN**?

Cheers
Pei

**Comment by atafra** [comment]
The error message suggests that the Git repository for OIDN was not cloned correctly. Git LFS is required (please see the documentation for details). If it's not installed, the tensor data will be corrupted (that's why you get this error message).

What do you mean by "backend Tensor"? Also, what do you mean by effectiveness specifically? There is a small test app called `tests` included, which runs a few tests.

Regards,
Attila
