### ISSUE TITLE
HDR denoising question

### ISSUE THREAD

**Issue by ColinChargyBentley** [OpenImageDenoise/oidn#91]
Hi @atafra or anyone else,
Quick question : does denoising HDR images with OIDN involves tone-mapping, then denoising LDR images then un-tone-mapping ? If so, what's the advantage of using OIDN tone-mapping if the host application has its own tonemapping fct ? I imagine speed may be one answer.

Best regards,
Colin Chargy

**Comment by atafra** [comment]
Hi Colin,

Denoising HDR images does indeed involve some kind of forward and inverse tone mapping internally but this is not equivalent to regular tone mapping. This is only an internal implementation detail and is not exposed to the user. Thus it's not a replacement for tone mapping performed by the application.

There is no significant speed difference between LDR and HDR denoising. If the application tone maps the image and discards the original HDR data, the image should be first tone mapped by the application and then denoised in LDR. This will ensure optimal image quality. Otherwise, the image should be denoised in HDR.

Best regards,
Attila

**Comment by ColinChargyBentley** [comment]
Hi @atafra,
Thanks a lot for these infos, that is helpful.
Regards,
Colin Chargy
